# Generated by Django 3.1.4 on 2020-12-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=12)),
                ('eiqama', models.CharField(max_length=10)),
                ('piqama', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=150)),
                ('requester', models.CharField(max_length=25)),
                ('clinicname', models.CharField(max_length=150)),
                ('ramount', models.IntegerField()),
                ('currency', models.CharField(max_length=25)),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
