# Generated by Django 3.1.4 on 2020-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='clinicname',
            field=models.CharField(max_length=150, verbose_name='العياده'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='currency',
            field=models.CharField(max_length=25, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='eiqama',
            field=models.CharField(max_length=10, verbose_name='هوية الموظف'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='empno',
            field=models.CharField(max_length=12, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المريض'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='note',
            field=models.CharField(max_length=500, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='piqama',
            field=models.CharField(max_length=16, verbose_name='هوية المريض'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ramount',
            field=models.IntegerField(verbose_name='مبلغ المطالبة'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='rdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='requester',
            field=models.CharField(max_length=25, verbose_name='مقدمة عن طريق'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('جديد', 'جديد'), ('تحت الاصدار', 'تحت الاصدار'), ('مرفوضه', 'مرفوضه')], max_length=50, verbose_name='الحالة'),
        ),
    ]
