# Generated by Django 3.1.4 on 2020-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_auto_20201215_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
