# Generated by Django 3.1.4 on 2020-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_auto_20201215_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='piqama',
            field=models.CharField(max_length=16, verbose_name='رقم بطاقةالمريض'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('جديد', 'جديد'), ('تحت الاصدار', 'تحت الاصدار'), ('مرفوضه', 'مرفوضه')], default='جديد', max_length=50, verbose_name='الحالة'),
        ),
    ]
