# Generated by Django 3.1.4 on 2020-12-16 08:24

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_auto_20201215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=claims.models.image_upload),
        ),
    ]
