# Generated by Django 3.1.4 on 2020-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_auto_20201216_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('جديد', '1'), ('تحت الاصدار', '2'), ('مرفوضه', '3'), ('مطلوب معلومات اضافيه', '4')], default='جديد', max_length=50, verbose_name='الحالة'),
        ),
    ]
