# Generated by Django 3.1.4 on 2020-12-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0007_auto_20201216_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مقدمة عن طريق'),
        ),
    ]
